hydra:
  searchpath:
  - file:///opt/NeMo/examples/nlp/language_modeling/conf
run:
  name: llama2_70b_bf16
  results_dir: /mnt/data/results/llama2_70b_bf16
  time_limit: 0-01:00:00
  dependency: singleton
trainer:
  num_nodes: 16
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: false
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 10
  max_time: '19:23:30:00'
  log_every_n_steps: 1
  val_check_interval: 10
  limit_val_batches: 32
  limit_test_batches: 50
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  explicit_log_dir: /mnt/data/results/llama2_70b_bf16/logs
  exp_dir: null
  name: megatron_llama
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_llama_pretrain
    name: llama2_70b_bf16
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: false
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: false
    save_nemo_on_train_end: true
    filename: megatron_llama--{val_loss:.2f}-{step}-{consumed_samples}
    model_parallel_size: 16
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
model:
  mcore_gpt: true
  micro_batch_size: 1
  global_batch_size: 256
  rampup_batch_size: null
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 4
  virtual_pipeline_model_parallel_size: 20
  encoder_seq_length: 4096
  max_position_embeddings: 4096
  num_layers: 80
  hidden_size: 8192
  ffn_hidden_size: 28672
  num_attention_heads: 64
  num_query_groups: 8
  init_method_std: 0.008944
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  apply_rope_fusion: true
  attention_type: multihead
  share_embeddings_and_output_weights: false
  tokenizer:
    library: sentencepiece
    type: null
    model: /mnt/data/tokenizer/tokenizer.model
    delimiter: null
    vocab_file: null
    merge_file: null
    sentencepiece_legacy: false
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: false
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: block
  activations_checkpoint_num_layers: 0
  num_micro_batches_with_partial_activation_checkpoints: 0
  activations_checkpoint_layers_per_pipeline: 0
  sequence_parallel: true
  transformer_engine: true
  fp8: false
  fp8_e4m3: false
  fp8_hybrid: false
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1
  fp8_amax_compute_algo: most_recent
  use_emha: false
  # ub_tp_comm_overlap: false
  ub_tp_comm_overlap: true
  tp_comm_atomic_ag: false
  tp_comm_atomic_rs: false
  use_flash_attention: true
  overlap_p2p_comm: true
  batch_p2p_comm: false
  gc_interval: 100
  nsys_profile:
    enabled: false
    trace:
    - nvtx
    - cuda
    start_step: 10
    end_step: 10
    ranks:
    - 0
    gen_shape: false
  optim:
    name: distributed_fused_adam
    lr: 0.00015
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    contiguous_param_buffer: true
    sched:
      name: CosineAnnealing
      warmup_steps: 2000
      constant_steps: 11873
      min_lr: 1.0e-05
    grad_sync_dtype: bf16
  data:
    data_impl: mmap
    splits_string: 99990,8,2
    seq_length: 4096
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix:
    - 1
    - /mnt/data/pile/my-gpt3_00_text_document
    # - 1
    # - /mnt/data/pile/my-gpt3_01_text_document
    # - 1
    # - /mnt/data/pile/my-gpt3_02_text_document
    # - 1
    # - /mnt/data/pile/my-gpt3_03_text_document
  ub_tp_comm_overlap_cfg:
    qkv_dgrad:
      method: bulk
      num_sm: 8
      cga_size: 2
      set_sm_margin: 0
    qkv_wgrad:
      method: bulk
      num_sm: 16
      cga_size: 2
      set_sm_margin: 0
    fc1_dgrad:
      method: bulk
      num_sm: 2
      cga_size: 2
      set_sm_margin: 0
    fc1_wgrad:
      method: bulk
      num_sm: 4
      cga_size: 2
      set_sm_margin: 0
    qkv_fprop:
      method: ring_exchange
      aggregate: 0
    proj_dgrad:
      method: ring_exchange
      aggregate: 0
    fc1_fprop:
      method: ring_exchange
      aggregate: 0
    fc2_dgrad:
      method: ring_exchange
      aggregate: 1
    proj_fprop:
      method: pipeline
      num_sm: 24
      cga_size: 2
      num_splits: 4
      set_sm_margin: 1
    fc2_fprop:
      method: pipeline
      num_sm: 16
      cga_size: 2
      num_splits: 4
      set_sm_margin: 1

